apiVersion: v2
name: postgres-only-example
description: Knative Service with CloudNativePG PostgreSQL
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ksvc
    version: ">=0.1.0"
    repository: "file://../../charts/library/ksvc"
